.TH MANGD.CONF 5
.SH NAME
.B mangd.conf
\- Mangrove daemon.
.SH DESCRIPTION
This manual page describes the
.B mangd(8)
configuration file.

.B mangd
execute a shell command when a process is terminated, according to links written in the
.R /etc/mangd.conf
file.

The links have the following format:

	'process command'->'shell command';

White spaces and newline are ignored outside of quotes, and each link is
terminad by a semicolon. Comments begin with a # and go to the end of the line.

The maximum process command len is KI_MAXCOMLEN - 1, and the maximum shell
command len is _POSIX2_MAX_LINE - 1;
.SH SEE ALSO
mangd(8)
