.TH MANGD 8 manglink\-VERSION
.SH NAME
mangd \- Mangrove daemon.
.SH SYNOPSIS
.B mangd
.RB [ \-d ]
.SH DESCRIPTION
.B mangd
is the daemon profram for the the tool Mangrove.
.B mangd
listen process death through kernel virtual memory, and allow the user to kill
some semanticly linked process, depending of the
.IR /etc/mangd.conf
file.

.B mangd
read
.IR /etc/mangd.conf continuously, so the configuration can be changed during
runtime. The daemon can be configured easily with
.B manglink(1) .
See the
.B mangd(5)
man page for configuration format.
.SH OPTIONS
.TP
.B \-d
Enable the debug mode (i.e. print warnigs and actions on the standard output)
.SH SEE ALSO
manglink(1), mangd.conf(5)
