.TH MANGLINK 1 manglink\-VERSION
.SH NAME
manglink \- creates formated links for mangd configuration file
.SH SYNOPSIS
.B manglink
.RB [ \-bcr ]
.RB [comm\ ...]
.SH DESCRIPTION
.B manglink
is a complementary tool for the mangrove daemon, which takes procs commands
through command line or standard input, and prints formatted
.IR mangd(1)
configuration link. The way given arguments are parsed, directly depends on
passed options (cf 
.IR OPTIONS
section).
.SH OPTIONS
.TP
.B \-b
manglink writes the links bidirectionally. The \-b option overrides the \-r one.
The links
.BR foo <\-> bar
will be considered as two separate links
.BR foo \-> bar
plus
.BR bar \-> foo .
.TP
.B \-c
manglink reads given arguments in a chained way.
.TP
.B \-r
manglink reverses each writen link.
.SH USAGE
manglink just writes to standard output, but should be used by redirecting the
output directly to
.IR /etc/mangd.conf .
.SH EXEMPLES
Writes links
.BR foo \-> bar \-> baz
to the standard output:

	$ manglink -c foo bar baz

Writes links
.BR foo \-> bar plus foo \-> baz
to
.IR /etc/mangd.conf:

	$ manglink foo bar baz

Writes links
.BR bar \-> foo
plus
.BR baz \-> foo
to the standard output:

	$ manglink -r foo bar baz

.SH SEE ALSO
mangd(8), mangd.conf(5)
