.TH MANGD 8 mangd\-VERSION
.SH NAME
mangd \- Mangrove daemon.
.SH SYNOPSIS
.B mangd
.RB [ \-d ]
.SH DESCRIPTION
.B mangd
is the daemon profram for the the Mangrove tool.
.B mangd
listens to process death through kernel virtual memory, and allows the user to kill
some semanticly linked processes, depending of the
.IR /etc/mangd.conf
file.

.B mangd
reads
.IR /etc/mangd.conf continuously, so the configuration can be changed during
runtime. The daemon can be configured easily with
.B manglink(1) .
See the
.B mangd(5)
man page for configuration format.
.SH OPTIONS
.TP
.B \-d
Enables the debug mode (i.e. print warnigs and logs on the standard output)
.SH SEE ALSO
manglink(1), mangd.conf(5)
