.TH MANGD.CONF 5
.SH NAME
.B mangd.conf
\- Mangrove daemon.
.SH DESCRIPTION
This manual page describes the
.B mangd(8)
configuration file.

.B mangd
manages process death according to link written in the
.R /etc/mangd.conf
file.

The links have the following format:

	'command1'->'command2';

command1 and command2 have to be process commands (i.e. same as the commands in
the COMMAND section of
.B top(1) .
White spaces and newline are ignored outside of quotes, and each link is
terminad by a semicolon.

Command can't contain a double quote (i.e. no escape with \\), and its size must
be between 0 and KI_MAXCOMLEN.
.SH SEE ALSO
manglink(1), mangd(8)
